### ISSUE TITLE
[BUG] Qiskit Job Result Fails with Custom-Named Classical Registers

### ISSUE THREAD

**Issue by Neerpatel125** [qBraid/qBraid#1010]
### Environment - Output of qbraid.about()

```
qBraid-SDK: A platform-agnostic quantum runtime framework
=========================================================
(C) 2025 qBraid Development Team (https://sdk.qbraid.com)

qbraid:	0.9.7

Core Dependencies
-----------------
numpy: 1.26.4
openqasm3: 1.0.1
pydantic: 2.9.2
pydantic-core: 2.23.4
pyqasm: 0.3.2
qbraid-core: 0.1.41
rustworkx: 0.16.0
typing-extensions: 4.14.0

Optional Dependencies
---------------------
amazon-braket-sdk: 1.91.2
attrs: 25.3.0
azure-identity: 1.23.0
azure-quantum: 2.2.0
azure-storage-blob: 12.20.0
cirq-core: 1.4.1
cirq-ionq: 1.4.1
ipython: 9.3.0
matplotlib: 3.10.3
packaging: 25.0
pandas: 2.3.0
ply: 3.11
pytket: 2.6.0
pytket-braket: 0.41.0
qbraid-qir: 0.3.2
qiskit: 2.1.0
qiskit-ibm-runtime: 0.38.0
qiskit-ionq: 0.5.12
qiskit-qasm3-import: 0.6.0
qiskit-qir: 0.5.0

Python: 3.12.10
Platform: Darwin (arm64)
```

### Context - Running in qBraid Lab?

No

### What happened?

The code fails to get the counts when the classical register has been named differently; it works if the register has been named "c" instead. 

### Code To Replicate Issue
```
from qbraid.runtime import QiskitRuntimeProvider
provider = QiskitRuntimeProvider(
    channel='ibm_quantum',
    instance='<INSTANCE>',
    token='<TOKEN>'
)
device = provider.get_device('ibm_sherbrooke')

from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
qr = QuantumRegister(2)
cr = ClassicalRegister(2, 'random')
circuit = QuantumCircuit(qr, cr)
circuit.h(0)
circuit.cx(0, 1)
circuit.measure([0, 1], [0, 1])
print(circuit.draw())
job = device.run(circuit, shots=10)
res = job.result()
print(res)
```
### Output
```
(metriq) neerpatel@MacBookPro desktop % python qBraid_bug.py 
/Users/neerpatel/miniforge3/envs/metriq/lib/python3.12/site-packages/qbraid/_entrypoints.py:20: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
          ┌───┐     ┌─┐   
    q0_0: ┤ H ├──■──┤M├───
          └───┘┌─┴─┐└╥┘┌─┐
    q0_1: ─────┤ X ├─╫─┤M├
               └───┘ ║ └╥┘
random: 2/═══════════╩══╩═
                     0  1 
/Users/neerpatel/miniforge3/envs/metriq/lib/python3.12/site-packages/qiskit_ibm_runtime/qiskit_runtime_service.py:875: UserWarning: IBM Quantum Platform is moving, and this version will be sunset on July 1. To get started on the new platform, read the migration guide at https://docs.quantum.ibm.com/migration-guides/classic-iqp-to-cloud-iqp
  warnings.warn(warning_message)
Traceback (most recent call last):
  File "/Users/neerpatel/Desktop/qBraid_bug.py", line 18, in <module>
    res = job.result()
          ^^^^^^^^^^^^
  File "/Users/neerpatel/miniforge3/envs/metriq/lib/python3.12/site-packages/qbraid/runtime/ibm/job.py", line 131, in result
    measurement_counts = builder.get_counts()
                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/neerpatel/miniforge3/envs/metriq/lib/python3.12/site-packages/qbraid/runtime/ibm/result_builder.py", line 73, in get_counts
    counts = [getattr(pub_result.data, attr).get_counts() for pub_result in self._result]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataBin' object has no attribute 'meas'
```

### Tags
@cosenal @vprusso @ryanhill1 @hrushikesh890

**Comment by ryanhill1** [comment]
@Neerpatel125 @hrushikesh890 Thanks for pointing out this bug!

Can you try out the changes introduced in https://github.com/qBraid/qBraid/pull/1011 and let me know if that fixes the issue? Seems to work on my end. If it also works for you, I'll write a test case and get it merged.

**Comment by Neerpatel125** [comment]
Thanks @ryanhill1 ! I tested the fix in the linked PR and it worked perfectly; I appreciate your help with this bug.
